'use client';
import { useEffect, useState } from 'react';
import { BottomNav } from '@/components/layout';
import { StoryRow } from '@/components/story-row';
import { UserCard } from '@/components/user-card';
import { apiFetch } from '@/lib/api';
import { getAccessToken } from '@/lib/auth';
import { DiscoverUser, Story } from '@/lib/types';
export default function DiscoverPage(){ const [users,setUsers]=useState<DiscoverUser[]>([]); const [stories,setStories]=useState<Story[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [radius,setRadius]=useState(10); const [gender,setGender]=useState(''); const [ageFrom,setAgeFrom]=useState(22); const [ageTo,setAgeTo]=useState(32);
 const loadData=async()=>{ if(!getAccessToken()){ window.location.href='/auth/login'; return; } setLoading(true); setError(''); try { const query = new URLSearchParams({lat:'10.7769',lng:'106.7009',radius:String(radius),ageFrom:String(ageFrom),ageTo:String(ageTo)}); if(gender) query.set('gender', gender); const [discoverUsers,feedStories]=await Promise.all([apiFetch<DiscoverUser[]>(`/users/discover?${query.toString()}`), apiFetch<Story[]>('/stories/feed')]); setUsers(discoverUsers); setStories(feedStories); } catch(err){ setError(err instanceof Error ? err.message : 'Không tải được dữ liệu'); } finally { setLoading(false); } };
 useEffect(()=>{ loadData(); },[]);
 return <div className="page"><div className="container"><div className="card" style={{ marginBottom: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><div className="brand">NearMatch</div><div className="muted">Gợi ý theo vị trí mẫu: Quận 1, TP.HCM</div></div><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><select className="select" style={{ width: 100 }} value={radius} onChange={(e)=>setRadius(Number(e.target.value))}><option value={5}>5km</option><option value={10}>10km</option><option value={20}>20km</option></select><select className="select" style={{ width: 120 }} value={gender} onChange={(e)=>setGender(e.target.value)}><option value="">Tất cả</option><option value="female">Nữ</option><option value="male">Nam</option></select><input className="input" style={{ width: 90 }} type="number" value={ageFrom} onChange={(e)=>setAgeFrom(Number(e.target.value))} /><input className="input" style={{ width: 90 }} type="number" value={ageTo} onChange={(e)=>setAgeTo(Number(e.target.value))} /><button className="btn btn-primary" type="button" onClick={loadData}>Lọc</button></div></div></div><div className="card" style={{ marginBottom: 20 }}><h3 style={{ marginTop: 0 }}>Story đang hoạt động</h3><StoryRow stories={stories} /></div>{error ? <div className="card" style={{ marginBottom: 20, color: '#be123c' }}>{error}</div> : null}{loading ? <div className="card">Đang tải danh sách gợi ý...</div> : null}<div className="grid-3">{!loading && users.map((user)=><UserCard key={user.id} user={user} onLiked={loadData} />)}</div>{!loading && users.length===0 ? <div className="card" style={{ marginTop: 20 }}>Chưa tìm thấy người phù hợp trong bộ lọc hiện tại.</div> : null}<BottomNav /></div></div>; }
