'use client';
import Image from 'next/image';
import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { BottomNav } from '@/components/layout';
import { apiFetch } from '@/lib/api';
import { getAccessToken } from '@/lib/auth';
import { MeResponse } from '@/lib/types';
const FALLBACK='https://placehold.co/240x240/png';
export default function EditProfilePage(){ const [me,setMe]=useState<MeResponse | null>(null); const [form,setForm]=useState({displayName:'',bio:'',jobTitle:'',city:'',latitude:'10.7769',longitude:'106.7009',interests:'coffee, travel, books',isLocationPrecise:'false',isStoryPublic:'true'}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); useEffect(()=>{ if(!getAccessToken()){ window.location.href='/auth/login'; return; } apiFetch<MeResponse>('/auth/me').then((data)=>{ setMe(data); setForm({displayName:data.displayName || '',bio:data.bio || '',jobTitle:data.jobTitle || '',city:data.city || '',latitude:data.latitude ? String(data.latitude) : '10.7769',longitude:data.longitude ? String(data.longitude) : '106.7009',interests:data.interests.map((i)=>i.interestName).join(', '),isLocationPrecise:String(Boolean(data.isLocationPrecise)),isStoryPublic:String(data.isStoryPublic ?? true)}); }).catch((err)=>setError(err instanceof Error ? err.message : 'Không tải được hồ sơ')).finally(()=>setLoading(false)); },[]); const updateField=(field:string,value:string)=>setForm((prev)=>({...prev,[field]:value})); const onSubmit=async(e:FormEvent)=>{ e.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const payload={displayName:form.displayName,bio:form.bio,jobTitle:form.jobTitle,city:form.city,latitude:Number(form.latitude),longitude:Number(form.longitude),interests:form.interests.split(',').map((i)=>i.trim()).filter(Boolean),isLocationPrecise:form.isLocationPrecise==='true',isStoryPublic:form.isStoryPublic==='true'}; const result=await apiFetch<{message:string; user:MeResponse}>('/users/me',{method:'PUT',body:JSON.stringify(payload)}); setMe(result.user); setMessage(result.message); } catch(err){ setError(err instanceof Error ? err.message : 'Không lưu được hồ sơ'); } finally { setSaving(false); } };
const uploadAvatar=async(event:ChangeEvent<HTMLInputElement>)=>{ const file=event.target.files?.[0]; if(!file) return; const formData=new FormData(); formData.append('file',file); try { const token=getAccessToken(); const response=await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3001/api'}/users/me/avatar`,{method:'PUT',headers: token ? { Authorization: `Bearer ${token}` } : undefined, body: formData}); if(!response.ok) throw new Error(await response.text()); const payload=await response.json(); setMe((prev)=> prev ? {...prev, avatarUrl: payload.user.avatarUrl} : prev); setMessage('Đã cập nhật avatar'); } catch(err){ setError(err instanceof Error ? err.message : 'Upload avatar thất bại'); } };
return <div className="page"><div className="container" style={{ maxWidth: 900 }}><div className="card"><h1 style={{ marginTop: 0 }}>Hồ sơ của tôi</h1>{loading ? <p>Đang tải hồ sơ...</p> : null}{error ? <p style={{ color: '#be123c' }}>{error}</p> : null}{message ? <p style={{ color: '#15803d' }}>{message}</p> : null}<div className="grid-2"><div><div className="card" style={{ textAlign: 'center', background: '#fdf2f8' }}><Image src={me?.avatarUrl || FALLBACK} alt="Avatar" width={140} height={140} style={{ width: 140, height: 140, borderRadius: 999, objectFit: 'cover', margin: '0 auto 12px' }} unoptimized /><input className="input" type="file" accept="image/*" onChange={uploadAvatar} /><p className="muted">Upload ảnh đại diện lên Cloudinary</p></div></div><div><form onSubmit={onSubmit}><div className="field"><label>Tên hiển thị</label><input className="input" value={form.displayName} onChange={(e)=>updateField('displayName',e.target.value)} /></div><div className="field"><label>Nghề nghiệp</label><input className="input" value={form.jobTitle} onChange={(e)=>updateField('jobTitle',e.target.value)} /></div><div className="field"><label>Thành phố</label><input className="input" value={form.city} onChange={(e)=>updateField('city',e.target.value)} /></div><div className="field"><label>Bio</label><textarea className="textarea" value={form.bio} onChange={(e)=>updateField('bio',e.target.value)} /></div><div className="field"><label>Sở thích</label><input className="input" value={form.interests} onChange={(e)=>updateField('interests',e.target.value)} /></div><div className="grid-2" style={{ gap: 12 }}><div className="field"><label>Latitude</label><input className="input" value={form.latitude} onChange={(e)=>updateField('latitude',e.target.value)} /></div><div className="field"><label>Longitude</label><input className="input" value={form.longitude} onChange={(e)=>updateField('longitude',e.target.value)} /></div></div><div className="field"><label>Chia sẻ vị trí chính xác</label><select className="select" value={form.isLocationPrecise} onChange={(e)=>updateField('isLocationPrecise',e.target.value)}><option value="false">Tắt</option><option value="true">Bật</option></select></div><div className="field"><label>Hiển thị story công khai</label><select className="select" value={form.isStoryPublic} onChange={(e)=>updateField('isStoryPublic',e.target.value)}><option value="true">Bật</option><option value="false">Tắt</option></select></div><button disabled={saving} className="btn btn-primary" type="submit">{saving ? 'Đang lưu...' : 'Lưu thay đổi'}</button></form></div></div></div><BottomNav /></div></div>; }
