'use client';
import Image from 'next/image';
import { FormEvent, useEffect, useState } from 'react';
import { BottomNav } from '@/components/layout';
import { StoryRow } from '@/components/story-row';
import { apiFetch } from '@/lib/api';
import { getAccessToken } from '@/lib/auth';
import { Story } from '@/lib/types';
const FALLBACK='https://placehold.co/800x500/png';
export default function StoriesPage(){ const [stories,setStories]=useState<Story[]>([]); const [selectedStory,setSelectedStory]=useState<Story | null>(null); const [caption,setCaption]=useState(''); const [textContent,setTextContent]=useState(''); const [mode,setMode]=useState<'text'|'image'>('text'); const [file,setFile]=useState<File | null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const loadStories=async()=>{ if(!getAccessToken()){ window.location.href='/auth/login'; return; } setLoading(true); try { const feed=await apiFetch<Story[]>('/stories/feed'); setStories(feed); setSelectedStory(feed[0] || null); } catch(err){ setError(err instanceof Error ? err.message : 'Không tải được stories'); } finally { setLoading(false); } }; useEffect(()=>{ loadStories(); },[]); const onSubmit=async(e:FormEvent)=>{ e.preventDefault(); setSaving(true); setError(''); try { const token=getAccessToken(); const formData=new FormData(); formData.append('mediaType',mode); formData.append('caption',caption); if(mode==='text') formData.append('textContent',textContent); if(mode==='image' && file) formData.append('file',file); const response=await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3001/api'}/stories`,{method:'POST',headers: token ? { Authorization: `Bearer ${token}` } : undefined, body: formData}); if(!response.ok) throw new Error(await response.text()); setCaption(''); setTextContent(''); setFile(null); await loadStories(); } catch(err){ setError(err instanceof Error ? err.message : 'Không đăng được story'); } finally { setSaving(false); } };
return <div className="page"><div className="container"><div className="card"><h1 style={{ marginTop: 0 }}>Story</h1>{loading ? <p>Đang tải story...</p> : <StoryRow stories={stories} />}{selectedStory ? (selectedStory.mediaType==='image' ? <Image src={selectedStory.mediaUrl || FALLBACK} alt="Story" width={1200} height={700} className="story-preview" unoptimized style={{ marginTop: 20 }} /> : <div className="story-preview" style={{ marginTop: 20, padding: 24, color: '#fff', display: 'flex', alignItems: 'end', fontSize: 24, fontWeight: 700 }}>{selectedStory.textContent}</div>) : <p className="muted">Chưa có story để xem.</p>}<p className="muted">{selectedStory?.caption || 'Chọn story để xem nội dung.'}</p><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>{stories.map((story)=><button key={story.id} className="btn btn-outline" type="button" onClick={()=>setSelectedStory(story)}>{story.user?.displayName || 'Story'}</button>)}</div></div><div className="card" style={{ marginTop: 20 }}><h2 style={{ marginTop: 0 }}>Đăng story mới</h2>{error ? <p style={{ color: '#be123c' }}>{error}</p> : null}<form onSubmit={onSubmit}><div className="field"><label>Loại story</label><select className="select" value={mode} onChange={(e)=>setMode(e.target.value as 'text'|'image')}><option value="text">Text</option><option value="image">Image</option></select></div>{mode==='image' ? <div className="field"><label>Chọn ảnh</label><input className="input" type="file" accept="image/*" onChange={(e)=>setFile(e.target.files?.[0] || null)} /></div> : <div className="field"><label>Nội dung text</label><textarea className="textarea" value={textContent} onChange={(e)=>setTextContent(e.target.value)} placeholder="Hôm nay của bạn thế nào?" /></div>}<div className="field"><label>Caption</label><input className="input" value={caption} onChange={(e)=>setCaption(e.target.value)} placeholder="Viết caption ngắn" /></div><button disabled={saving} className="btn btn-primary" type="submit">{saving ? 'Đang đăng...' : 'Đăng story'}</button></form></div><BottomNav /></div></div>; }
